### ISSUE TITLE
Conservation of Energy

### ISSUE THREAD

**Issue by juso40** [ECP-copa/CabanaPIC#44]
Am I correct with the assumption that the printed steps should ideally all show the same energy values?
I'm currently looking for different proxy-applications to compare tapered floating points with, and this project seemed well-structured to work for my case.

I'm just unsure of the printed results, as I don't know much behind the special physics involved. But from my limited understanding, the energies printed each step should ideally be identical at each step. This obviously is not possible with floating point arithmetic, but with higher precision, eg doubles instead of floats, the results should generally vary less between each step.

**Comment by streeve** [comment]
@guangyechen I think you're the most familiar with the precision/conservation here - can you give some detail?

**Comment by guangyechen** [comment]
Yes. The total energy (which in PIC is the sum of kinetic energy of particles and field energy) should be conserved (if there is no energy source or sink which is the case in our examples).

**Comment by juso40** [comment]
Thank you. Is there any paper/publication that I could cite when referencing this proxy-app?

**Comment by streeve** [comment]
We have an overview of our project with brief description of CabanaPIC (entirely up to you to cite or not given your context) here: https://journals.sagepub.com/doi/full/10.1177/10943420211022829 and a brand new release here: https://zenodo.org/record/7672323#.Y_glOrTMLao

**Comment by juso40** [comment]
Awesome, thank you. 
This is essentially part of my bachelor thesis, so I just need some sort of source for my information about CabanaPIC. Those two links should suffice.
And I think all my questions got answered, so feel free to close this issue if you'd like.
